### ISSUE TITLE
Use Printer API

### ISSUE THREAD

**Issue by goodmind** [ikatyang/dts-element#1]
https://github.com/Microsoft/TypeScript/pull/13940
https://github.com/Microsoft/TypeScript/pull/13761

**Comment by ikatyang** [comment]
Thanks for the suggestion.

I noticed that the Printer API is powerful, but to use it, I have to adapt the dts-element to the TS AST, which will take a lot of time since there aren't detailed informations in the [documentation](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API).

I have tried for hours and still having a lots of problems, I'll wait for enough information to do such work.
